# fly.toml app configuration file generated for edutech--cold-dream-305 on 2024-04-26T15:37:44-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'edutech--cold-dream-305'
primary_region = 'scl'

[build]

[http_service]
  internal_port = 3039
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
