name: Despliegue del backend

on:
  push:
    branches:
      - backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Compilar aplicación
        run: |
          # Compilar la aplicación con Maven
          mvn clean package -DskipTests

      - name: Desplegar aplicación
        run: |
          # Configurar la base de datos en el entorno de producción
          export DATABASE_URL='mysql://uphlrap4jho52sxm:H6Ract7DiaK09oeYjmOI@bpbrow7nzuvik4o584fx-mysql.services.clever-cloud.com:3306/bpbrow7nzuvik4o584fx'

          # Ejecutar la aplicación Spring Boot
           java -jar target/servicioss-0.0.1-SNAPSHOT.jar


